spring:
  datasource:
    url: jdbc:postgresql://dpg-chcc5uu7avjcvo74sj0g-a.oregon-postgres.render.com/erp_yjhy
    username: erp_yjhy_user
    password: ta5LeFLINtCb2uhVByc5xtG7CbsFZqug
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

