# ============== ubuntu mysql info ==========

spring:
  datasource:
    password: Root@#_88888888
    username: root
    url: jdbc:mysql://localhost:3306/erp
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


      # ============== demo ==========
#      spring:
#        datasource:
#          url: jdbc:postgresql://dpg-cgct3sndvk4htnq4hbfg-a.oregon-postgres.render.com/borrowmybook_bz9i
#          username: borrowmybook_user
#          password: hMBChitOx4iFDBDMV9gfP6z69p8NLbTM
#        jpa:
#          show-sql: true
#          properties:
#            hibernate:
#              dialect: org.hibernate.dialect.PostgreSQLDialect
#          hibernate:
#            ddl-auto: update


      # ============== database created for this project information ==========

#      Connections
#
#      Hostname
#      dpg-chcc5uu7avjcvo74sj0g-a
#
#      Port
#      5432
#
#      Database
#      erp_yjhy
#
#      Username
#      erp_yjhy_user
#
#      Password
#      ta5LeFLINtCb2uhVByc5xtG7CbsFZqug
#
#      Internal Database URL
#      postgres://erp_yjhy_user:ta5LeFLINtCb2uhVByc5xtG7CbsFZqug@dpg-chcc5uu7avjcvo74sj0g-a/erp_yjhy
#
#      External Database URL
#      postgres://erp_yjhy_user:ta5LeFLINtCb2uhVByc5xtG7CbsFZqug@dpg-chcc5uu7avjcvo74sj0g-a.oregon-postgres.render.com/erp_yjhy
#
#      PSQL Command
#      PGPASSWORD=ta5LeFLINtCb2uhVByc5xtG7CbsFZqug psql -h dpg-chcc5uu7avjcvo74sj0g-a.oregon-postgres.render.com -U erp_yjhy_user erp_yjhy