spring:
  datasource:
    password: Root@#_88888888
    username: root
    url: jdbc:mysql://localhost:3306/erp
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update